const { Schema, model } = require("mongoose")
const modelNames = require("./ModelNames")

const Info = Schema({
    currentMonth: {type: Number, default: 0},
    currentMonthRegisteredServices: {
        day1: {type: Number, default: 0},
        day2: {type: Number, default: 0},
        day3: {type: Number, default: 0},
        day4: {type: Number, default: 0},
        day5: {type: Number, default: 0},
        day6: {type: Number, default: 0},
        day7: {type: Number, default: 0},
        day8: {type: Number, default: 0},
        day9: {type: Number, default: 0},
        day10: {type: Number, default: 0},
        day11: {type: Number, default: 0},
        day12: {type: Number, default: 0},
        day13: {type: Number, default: 0},
        day14: {type: Number, default: 0},
        day15: {type: Number, default: 0},
        day16: {type: Number, default: 0},
        day17: {type: Number, default: 0},
        day18: {type: Number, default: 0},
        day19: {type: Number, default: 0},
        day20: {type: Number, default: 0},
        day21: {type: Number, default: 0},
        day22: {type: Number, default: 0},
        day23: {type: Number, default: 0},
        day24: {type: Number, default: 0},
        day25: {type: Number, default: 0},
        day26: {type: Number, default: 0},
        day27: {type: Number, default: 0},
        day28: {type: Number, default: 0},
        day29: {type: Number, default: 0},
        day30: {type: Number, default: 0},
    },
    currentMonthRegisteredSellers: {
        day1: {type: Number, default: 0},
        day2: {type: Number, default: 0},
        day3: {type: Number, default: 0},
        day4: {type: Number, default: 0},
        day5: {type: Number, default: 0},
        day6: {type: Number, default: 0},
        day7: {type: Number, default: 0},
        day8: {type: Number, default: 0},
        day9: {type: Number, default: 0},
        day10: {type: Number, default: 0},
        day11: {type: Number, default: 0},
        day12: {type: Number, default: 0},
        day13: {type: Number, default: 0},
        day14: {type: Number, default: 0},
        day15: {type: Number, default: 0},
        day16: {type: Number, default: 0},
        day17: {type: Number, default: 0},
        day18: {type: Number, default: 0},
        day19: {type: Number, default: 0},
        day20: {type: Number, default: 0},
        day21: {type: Number, default: 0},
        day22: {type: Number, default: 0},
        day23: {type: Number, default: 0},
        day24: {type: Number, default: 0},
        day25: {type: Number, default: 0},
        day26: {type: Number, default: 0},
        day27: {type: Number, default: 0},
        day28: {type: Number, default: 0},
        day29: {type: Number, default: 0},
        day30: {type: Number, default: 0},
    }

})

module.exports = model(modelNames.INFO, Info)